# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 665e9375580124acf35ab48e0886d2d0a49f3066f0534c433eaab0fe4dae3db8fb1e5973ab6eda5fea4296941bdc216dbfb5af48d13ff43492dc4199fc6e5d2a

test:
  secret_key_base: 4e2546ed2ac8ebec0bb7bccd0d52685562ed9bec85b4393f3074d460d6b2dc04565d1372f8bd3e7acd00cd059837c515e5f51975b37a26072ecf9bd911f203e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
